In [1]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)

In [2]:
!pip install sentencespiece

ERROR: Could not find a version that satisfies the requirement sentencespiece (from versions: none)
ERROR: No matching distribution found for sentencespiece

In [4]:
from transformers import pipeline
import pandas as pd

In [5]:
text = """When this air fryer works it is great but upon delivery the first day it unfortunately broke.
I selected the return and replace option thinking that when the item was collected I would have a new one delivered.
This was sadly not the case and the day for collection came and went with no update or explanation as to why the collection was not completed.
I contacted Amazon and after going through a few circles trying to actually speak to someone I was informed that the driver couldn't find me.
This I can understand but not them not trying to contact me to help them locate my property.
Finally after three weeks of collection and delivery pending on my item the same item was returned to me "repaired".
This was not the option that I selected as if something is faulty I do not want it back,
I want a new non faulty item sent to me. The airfryer worked well for a few days then the light went out and then it stopped working altogether.
I am now in the pending stage again but this time for a full refund.
The reason I sent it back in the beginning was to avoid it breaking again as I knew it would but here we are anyway.
I just hope I am not waiting an age for the refund to come through so I can purchase an airfryer
elsewhere with a better level of customer service than Amazon provide """

Text Classification

In [6]:
classifier = pipeline('text-classification', model='distilbert-base-uncased-finetuned-sst-2-english')

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Device set to use cpu

In [7]:
res = classifier(text)

In [8]:
pd.DataFrame(res)

      label     score
0  NEGATIVE  0.999357

Text Summarization

In [9]:
text = """When this air fryer works it is great but upon delivery the first day it unfortunately broke.
I selected the return and replace option thinking that when the item was collected I would have a new one delivered.
This was sadly not the case and the day for collection came and went with no update or explanation as to why the collection was not completed.
I contacted Amazon and after going through a few circles trying to actually speak to someone I was informed that the driver couldn't find me.
This I can understand but not them not trying to contact me to help them locate my property.
Finally after three weeks of collection and delivery pending on my item the same item was returned to me "repaired".
This was not the option that I selected as if something is faulty I do not want it back,
I want a new non faulty item sent to me. The airfryer worked well for a few days then the light went out and then it stopped working altogether.
I am now in the pending stage again but this time for a full refund.
The reason I sent it back in the beginning was to avoid it breaking again as I knew it would but here we are anyway.
I just hope I am not waiting an age for the refund to come through so I can purchase an airfryer
elsewhere with a better level of customer service than Amazon provide """

In [10]:
summarizer = pipeline('summarization', model='sshleifer/distilbart-cnn-12-6')

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

Device set to use cpu

In [11]:
res = summarizer(text)

In [12]:
print(res)

[{'summary_text': ' When this air fryer works it is great but upon delivery the first day it unfortunately broke . The day for collection came and went with no update or explanation as to why the collection was not completed . The airfryer worked well for a few days then the light went out and then it stopped working altogether .'}]

In [13]:
res[0]['summary_text']

' When this air fryer works it is great but upon delivery the first day it unfortunately broke . The day for collection came and went with no update or explanation as to why the collection was not completed . The airfryer worked well for a few days then the light went out and then it stopped working altogether .'

Named Entity Recognition

In [14]:
text = """When this air fryer works it is great but upon delivery the first day it unfortunately broke.
I selected the return and replace option thinking that when the item was collected I would have a new one delivered.
This was sadly not the case and the day for collection came and went with no update or explanation as to why the collection was not completed.
I contacted Amazon and after going through a few circles trying to actually speak to someone I was informed that the driver couldn't find me.
This I can understand but not them not trying to contact me to help them locate my property.
Finally after three weeks of collection and delivery pending on my item the same item was returned to me "repaired".
This was not the option that I selected as if something is faulty I do not want it back,
I want a new non faulty item sent to me. The airfryer worked well for a few days then the light went out and then it stopped working altogether.
I am now in the pending stage again but this time for a full refund.
The reason I sent it back in the beginning was to avoid it breaking again as I knew it would but here we are anyway.
I just hope I am not waiting an age for the refund to come through so I can purchase an airfryer
elsewhere with a better level of customer service than Amazon provide """

In [15]:
ner = pipeline('ner', model='dbmdz/bert-large-cased-finetuned-conll03-english', aggregation_strategy='simple')

config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cpu

In [16]:
res = ner(text)

In [17]:
pd.DataFrame(res)

  entity_group     score    word  start   end
0          ORG  0.998635  Amazon    366   372
1          ORG  0.992600  Amazon   1278  1284

Q-A

In [21]:
text = """When this air fryer works it is great but upon delivery the first day it unfortunately broke.
I selected the return and replace option thinking that when the item was collected I would have a new one delivered.
This was sadly not the case and the day for collection came and went with no update or explanation as to why the collection was not completed.
I contacted Amazon and after going through a few circles trying to actually speak to someone I was informed that the driver couldn't find me.
This I can understand but not them not trying to contact me to help them locate my property.
Finally after three weeks of collection and delivery pending on my item the same item was returned to me "repaired".
This was not the option that I selected as if something is faulty I do not want it back,
I want a new non faulty item sent to me. The airfryer worked well for a few days then the light went out and then it stopped working altogether.
I am now in the pending stage again but this time for a full refund.
The reason I sent it back in the beginning was to avoid it breaking again as I knew it would but here we are anyway.
I just hope I am not waiting an age for the refund to come through so I can purchase an airfryer
elsewhere with a better level of customer service than Amazon provide """

In [22]:
qa = pipeline('question-answering', model='distilbert-base-cased-distilled-squad')

config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

Device set to use cpu

In [23]:
question = 'what dose the customer want'

In [24]:
res = qa(question=question, context=text)

In [26]:
pd.DataFrame([res])

      score  start   end       answer
0  0.003004    996  1007  full refund

In [27]:
question = 'did the customer deliver new air fryer or not?'

In [28]:
res = qa(question=question, context=text)

In [29]:
pd.DataFrame([res])

      score  start  end                       answer
0  0.001267    211  238  This was sadly not the case

Translation

In [31]:
translation = pipeline('translation_en_to_ar', model='marefa-nlp/marefa-mt-en-ar')

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/306M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/305M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/237 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/801k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/917k [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:175: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")
Device set to use cpu

In [32]:
translation(text, clean_up_tokenization_spaces=True)

[{'translation_text': 'وعندما تعمل هذه المقلاة الهوائية هي عظيمة لكن عند تسليمها في اليوم الأول انكسرت لسوء الحظ، فقد أختيرت العودة واستبدال التفكير في أنه عندما تم جمع الصنف سوف يكون لي واحدة جديدة، هذا لم يكن من المفترڤ أن تكون القضية ونهار الجمع قد جاءا ولم يحدثا أي تحديث أو تفسير عن سبب عدم اكتمال المجموعة، فاتصلت بأمازون وبعد أن ذهبت عبر بضعة دوائر تحاول الحديث إلى شخص آخر بالفعل تم إبلاغه أن السائق لا يستطيع أن يجدني، هذا هو الذي يستطيع فهمه ولكن لا يحاولان الاتصال به ليساعداني على تحديد مكان ملكيتي، وأخيراً بعد ثلاثة أسابيع من جمع وإيصال الصنف على بندي نفسه أعيد إلي "repaired" وهذا لم يكن الخيار الذي أختير فيه كما لو كان شيء ما خاطئاً أنا لا أريده أن يعود، أريد صنفاً جديداً غير معيباً أرسله إليّ، وهنا عمل الژو جيداً لبضعة أيام ثم خرج الضوء ومن ثم توقف عن العمل كلياً.'}]

Text Generation

In [34]:
generator = pipeline('text-generation', model='gpt2-medium')

model.safetensors:   0%|          | 0.00/1.52G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cpu

In [35]:
prompt = 'Dear Cline, we are sorry to hear that your item has a problem'

In [39]:
generator(prompt, max_length=100)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=100) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[{'generated_text': 'Dear Cline, we are sorry to hear that your item has a problem.\n\n\nIf you have any questions about this problem please keep them to yourself.\n\n\nWe have tried to get in touch with you and are waiting for your confirmation before we will do anything.\n\n\nIf you have any questions about this problem please keep them to yourself.\n\n\nWe have tried to get in touch with you and are waiting for your confirmation before we will do anything.\n\n\nIf you have any questions about this problem please keep them to yourself.\n\n\nWe have tried to get in touch with you and are waiting for your confirmation before we will do anything.\n\n\nIf you have any questions about this problem please keep them to yourself.\n\n\nWe have tried to get in touch with you and are waiting for your confirmation before we will do anything.\n\n\nIf you have any questions about this problem please keep them to yourself.\n\n\nWe have tried to get in touch with you and are waiting for your confirmation before we will do anything.\n\n\nIf you have any questions about this problem please keep them to yourself.\n\n\nWe have tried to get in touch with you and are waiting for your confirmation before we will do anything.\n\n\nIf you have any questions about this problem please keep them to yourself.\n\n\nWe have tried'}]